apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cgm-role-binding
subjects:
  - kind: ServiceAccount
    name: cgm-sa
roleRef:
  kind: Role
  name: cgm-role
  apiGroup: rbac.authorization.k8s.io