apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cgm-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - cgm.cluster.cgm-azure.pp.ua
      secretName: cgm-certificate-secret
  rules:
    - host: cgm.cluster.cgm-azure.pp.ua
      http:
        paths:
          - backend:
              service:
                name: cgm-service
                port:
                  number: 80
            path: /
            pathType: Prefix