apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aksplorer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
